import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { motion } from "framer-motion";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zeus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial="hidden"
        animate="visible"
        variants={{
          hidden: {
            scale: 0.8,
            opacity: 0,
          },
          visible: {
            scale: 1,
            opacity: 1,
            transition: {
              delay: 0.4,
            },
          },
        }}
        whileHover={{
          scale: 1.2,
          transition: {
            duration: 0.1,
          },
        }}
      >
        <div className={styles.center}>
          <h1 className="title">Hello World!</h1>
          <div className={styles.linksContainer}>
            <Link href="/about">
              <a className={styles.link}>About</a>
            </Link>
            <Link href="/careers">
              <a className={styles.link}>Careers</a>
            </Link>
            <Link href="/blog">
              <a className={styles.link}>Blog</a>
            </Link>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default Home;
